import { useNavigate } from 'react-router-dom'
import '../css/Game.css'
import Footer from '../components/Footer'
import Banner from '../components/Banner'
import { useState, useEffect } from 'react'
import { motion, AnimatePresence } from 'framer-motion'

interface GameProps {
  onBack: () => void;
}

interface Mob {
  id: string;
  name: string;
  variant: string | null;
  combatLevel: number;
  image: string;
  color: string | null;
  wikiUrl: string;
}

interface Dataset {
  version: number;
  generatedAt: string;
  mobs: Mob[];
}

// Generated by SCRAPER/ and served alongside the game
const DATA_URL = `${import.meta.env.BASE_URL}data/mobs.json`;
const DEFAULT_LEFT_COLOR = '#2d5016';
const DEFAULT_RIGHT_COLOR = '#8b0000';

// Show the bare monster name, cutting off any bracketed text (including nested brackets)
function displayName(mob: Mob): string {
    let name = mob.name;
    let previous;
    do {
        previous = name;
        name = name.replace(/\s*\([^()]*\)/g, '');
    } while (name !== previous);
    return name.trim();
}
const randomIndex = (length: number) => Math.floor(Math.random() * length);

// Group by displayed name so each monster is equally likely, however many variants it has,
// and so two mobs that would show the same name are never paired
function groupByMonster(mobs: Mob[]): Mob[][] {
    const groups = new Map<string, Mob[]>();
    for (const mob of mobs) {
        const key = displayName(mob);
        const group = groups.get(key);
        if (group) group.push(mob);
        else groups.set(key, [mob]);
    }
    return [...groups.values()];
}

// Pick two different monsters (never two variants of the same one), then a variant of each
function pickPair(groups: Mob[][]): [Mob, Mob] {
    const i = randomIndex(groups.length);
    let j = randomIndex(groups.length - 1);
    if (j >= i) j += 1;
    const pick = (group: Mob[]) => group[randomIndex(group.length)];
    return [pick(groups[i]), pick(groups[j])];
}

//not sold on the box game look, mayb try without the box?
function Game({ onBack }: GameProps){
    const [groups, setGroups] = useState<Mob[][]>([]);
    const [loadError, setLoadError] = useState<string | null>(null);
    const [pair, setPair] = useState<[Mob, Mob] | null>(null);
    const [score, setScore] = useState<number>(0);
    const [highScore, setHighScore] = useState<number>(0);
    const [gameOver, setGameOver] = useState<boolean>(false);
    const [reveal, setReveal] = useState(false);
    const [roundKey, setRoundKey] = useState(0);
    const [pickedSide, setPickedSide] = useState<null | 'left' | 'right'>(null);
    const [lastCorrect, setLastCorrect] = useState<boolean | null>(null);

    const nextRound = (fromGroups: Mob[][] = groups) => {
        setPair(pickPair(fromGroups));
        setReveal(false);
        setPickedSide(null);
        setLastCorrect(null);
        setRoundKey(prev => prev + 1);
    };

    const handlePlayAgain = () => {
        setScore(0);
        setGameOver(false);
        nextRound();
    };

    // On mount, load the dataset and start the first round
    useEffect(() => {
        let cancelled = false;
        fetch(DATA_URL)
            .then(res => {
                if (!res.ok) throw new Error(`HTTP error! status: ${res.status}`);
                return res.json() as Promise<Dataset>;
            })
            .then(data => {
                if (cancelled) return;
                const loaded = groupByMonster(data.mobs);
                if (loaded.length < 2) throw new Error('Not enough mobs in dataset');
                setGroups(loaded);
                nextRound(loaded);
            })
            .catch(error => {
                if (cancelled) return;
                console.error('Error loading mob dataset:', error);
                setLoadError('Failed to load mobs. Please try again later.');
            });
        // Ignore a stale load if the component unmounts (or StrictMode re-runs the effect)
        return () => { cancelled = true; };
        // eslint-disable-next-line
    }, []);

    // Handle user guess (left or right)
    const handleGuess = (guess: 'left' | 'right') => {
        if (!pair || gameOver || reveal) return;
        const [left, right] = pair;
        const correct = guess === 'left'
            ? left.combatLevel >= right.combatLevel
            : right.combatLevel >= left.combatLevel;
        setPickedSide(guess);
        setLastCorrect(correct);
        setReveal(true);
        if (correct) {
            const newScore = score + 1;
            setScore(newScore);
            if (newScore > highScore) setHighScore(newScore);
            setTimeout(() => nextRound(), 1500);
        } else {
            setTimeout(() => {
                setGameOver(true);
            }, 3000);
        }
    };

    const slideDownAnimation = {
        initial: { y: -100, opacity: 0 },
        animate: { y: 0, opacity: 1 },
        transition: { 
            duration: 0.8, 
            ease: "easeOut",
            delay: 0.2
        }
    };

    // Animation for combat level reveal
    const combatLevelRevealAnim = {
        initial: { opacity: 0, scale: 0.7 },
        animate: { opacity: 1, scale: 1, transition: { duration: 0.4, ease: 'easeOut' } }
    };

    // Animation for mob box exit
    const leftExitAnim = { exit: { x: '-100vw', opacity: 0, transition: { duration: 0.4, ease: 'easeIn' } } };
    const rightExitAnim = { exit: { x: '100vw', opacity: 0, transition: { duration: 0.4, ease: 'easeIn' } } };

    // Determine the color of the center circle based on selection
    const orCircleColor =
      pickedSide && reveal
        ? lastCorrect
          ? "#2ecc40" // green
          : "#e74c3c" // red
        : "#fff"; // default white

    // Determine the icon for the center circle
    const orCircleIcon =
      pickedSide && reveal
        ? lastCorrect
          ? "✔"
          : "✖"
        : "OR";

    if (loadError) {
        return (
            <div className="game-container">
                <p className="game-error">{loadError}</p>
            </div>
        );
    }
    if (!pair) {
        return (
            <div className="game-container">
                <div className="game-throbber"></div>
            </div>
        );
    }
    const [left, right] = pair;
    return (
        <div className="game-container">
            <div className="backdrop" />
            <div className="game__box game__box--with-divider">
                {gameOver ? (
                  <div className="gameover-overlay">
                    <motion.div
                      className="gameover-content"
                      initial={{ y: -200, opacity: 0 }}
                      animate={{ y: 0, opacity: 1 }}
                      transition={{ type: "spring", stiffness: 300, damping: 30 }}
                    >
                        <h1 className="gameover-title">You Scored</h1>
                        <div className="gameover-score"><p>{score}</p></div>
                        <button className="gameover-btn" onClick={handlePlayAgain}>Play Again</button>
                    </motion.div>
                  </div>
                ) : (
                  <>
                    <AnimatePresence mode="wait">
                        <motion.div 
                            key={"left-" + roundKey}
                            className={
                              "gamebox__left" +
                              (pickedSide === 'left' && reveal
                                ? lastCorrect
                                  ? " gamebox__picked-correct"
                                  : " gamebox__picked-incorrect"
                                : "")
                            }
                            initial={slideDownAnimation.initial}
                            animate={slideDownAnimation.animate}
                            exit={leftExitAnim.exit}
                            transition={slideDownAnimation.transition}
                            onClick={() => handleGuess('left')}
                            style={{ cursor: gameOver || reveal ? 'not-allowed' : 'pointer' }}
                        >
                            <div 
                                className="gamebox__background"
                                style={{ backgroundColor: left.color ?? DEFAULT_LEFT_COLOR }}
                            />
                            <div className="gamebox__label">
                                {displayName(left)}
                                {reveal && (
                                    <motion.div
                                        className="combat-level"
                                        initial={combatLevelRevealAnim.initial}
                                        animate={combatLevelRevealAnim.animate}
                                    >
                                        Level {left.combatLevel}
                                    </motion.div>
                                )}
                            </div>
                            <img className="gamebox__image" src={left.image} alt={displayName(left)} />
                        </motion.div>
                    </AnimatePresence>

                    <div
                      className="gamebox__or-circle"
                      style={{ background: orCircleColor, transition: 'background 0.3s' }}
                    >
                      <span className={pickedSide && reveal ? "or-circle-icon" : undefined}>{orCircleIcon}</span>
                    </div>

                    <div className="gamebox__score">
                        <div className="score__current">Score: {score}</div>
                        <div className="score__high">High Score: {highScore}</div>
                    </div>

                    <AnimatePresence mode="wait">
                        <motion.div 
                            key={"right-" + roundKey}
                            className={
                              "gamebox__right" +
                              (pickedSide === 'right' && reveal
                                ? lastCorrect
                                  ? " gamebox__picked-correct"
                                  : " gamebox__picked-incorrect"
                                : "")
                            }
                            initial={slideDownAnimation.initial}
                            animate={slideDownAnimation.animate}
                            exit={rightExitAnim.exit}
                            transition={{ ...slideDownAnimation.transition, delay: 0.4 }}
                            onClick={() => handleGuess('right')}
                            style={{ cursor: gameOver || reveal ? 'not-allowed' : 'pointer' }}
                        >
                            <div 
                                className="gamebox__background"
                                style={{ backgroundColor: right.color ?? DEFAULT_RIGHT_COLOR }}
                            />
                            <div className="gamebox__label">
                                {displayName(right)}
                                {reveal && (
                                    <motion.div
                                        className="combat-level"
                                        initial={combatLevelRevealAnim.initial}
                                        animate={combatLevelRevealAnim.animate}
                                    >
                                        Level {right.combatLevel}
                                    </motion.div>
                                )}
                            </div>
                            <img className="gamebox__image" src={right.image} alt={displayName(right)} />
                        </motion.div>
                    </AnimatePresence>
                  </>
                )}
            </div>
        </div>
    );
}

export default Game;